# Generated by Django 5.2.7 on 2025-10-17 05:35

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ModelMetric',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='모델 이름')),
                ('metric_name', models.CharField(default='request_duration_seconds', max_length=100, verbose_name='메트릭 이름')),
                ('p50_latency_ms', models.FloatField(blank=True, null=True, verbose_name='P50 레이턴시 (ms)')),
                ('p95_latency_ms', models.FloatField(blank=True, null=True, verbose_name='P95 레이턴시 (ms)')),
                ('p99_latency_ms', models.FloatField(blank=True, null=True, verbose_name='P99 레이턴시 (ms)')),
                ('time_range', models.CharField(default='5m', max_length=20, verbose_name='시간 범위')),
                ('collected_at', models.DateTimeField(default=django.utils.timezone.now, verbose_name='수집 시간')),
                ('prometheus_timestamp', models.FloatField(blank=True, null=True, verbose_name='Prometheus 타임스탬프')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='수정 시간')),
            ],
            options={
                'verbose_name': '모델 메트릭',
                'verbose_name_plural': '모델 메트릭',
                'ordering': ['-collected_at', 'model_name'],
                'indexes': [models.Index(fields=['model_name', '-collected_at'], name='api_modelme_model_n_6a4643_idx'), models.Index(fields=['-collected_at'], name='api_modelme_collect_f4816f_idx')],
            },
        ),
        migrations.CreateModel(
            name='ModelMetricHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=100, verbose_name='모델 이름')),
                ('metric_name', models.CharField(default='request_duration_seconds', max_length=100, verbose_name='메트릭 이름')),
                ('p95_latency_ms', models.FloatField(verbose_name='P95 레이턴시 (ms)')),
                ('timestamp', models.DateTimeField(db_index=True, verbose_name='타임스탬프')),
                ('prometheus_timestamp', models.FloatField(blank=True, null=True, verbose_name='Prometheus 타임스탬프')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='생성 시간')),
            ],
            options={
                'verbose_name': '모델 메트릭 히스토리',
                'verbose_name_plural': '모델 메트릭 히스토리',
                'ordering': ['-timestamp', 'model_name'],
                'indexes': [models.Index(fields=['model_name', '-timestamp'], name='api_modelme_model_n_28a4a9_idx'), models.Index(fields=['-timestamp'], name='api_modelme_timesta_7390e7_idx')],
            },
        ),
    ]
